# Generated by Django 4.2.29 on 2026-03-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProjectTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(unique=True)),
                ("color", models.CharField(default="#0EA5E9", max_length=20)),
            ],
            options={
                "verbose_name": "Project Tag",
                "verbose_name_plural": "Project Tags",
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=250, unique=True)),
                ("description", models.TextField()),
                ("short_description", models.CharField(blank=True, max_length=300)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                (
                    "gallery",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of additional image URLs",
                    ),
                ),
                ("github_link", models.URLField(blank=True)),
                ("live_link", models.URLField(blank=True)),
                ("featured", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "technologies",
                    models.ManyToManyField(
                        blank=True, related_name="projects", to="projects.projecttag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Project",
                "verbose_name_plural": "Projects",
                "ordering": ["-featured", "-order", "-created_at"],
            },
        ),
    ]
